---
- name: 'Single Node Openshift Deployment on Libvirt'
  hosts: provisioner
  vars:
    version: "latest-4.8"
    build: "ga"

  tasks:

  - name: "Prepare SNO Host"
    import_role:
      name: sno-node-prep

  - name: "Deploy SNO VM"
    import_role:
      name: sno-installer
