---
- name: Copy PullSecret into {{ pullsecret_file }}
  copy:
    content: "{{ pullsecret }}"
    dest: "{{ pullsecret_file }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0644'
    force: yes
  tags:
  - pullsecret
  - extract

- name: Create config dir
  file:
    path: "{{ dir }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0755'
  tags:
  - extract

- name: Confirm whether or not internet connectivity on provisioner host
  uri:
    url: https://www.redhat.com
    status_code: [-1,200]
    timeout: 1
  register: the_url
  tags:
  - extract

- name: Extracting the installer
  command: |
          /usr/local/bin/oc adm release extract --registry-config {{ pullsecret_file | quote }} --command={{ cmd |quote }} --to {{ tempdir | quote }} {{ release_image }}
  args:
    chdir: "{{ tempdir }}"
  when: (the_url.status == 200)
  tags: extract

- name: Copy openshift-install binary to /usr/local/bin
  copy:
    src: "{{ tempdir }}/{{ cmd }}"
    dest: /usr/local/bin/
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0755'
    remote_src: yes
  become: yes
  tags: extract
