---
- name: Get COMMIT_ID
  shell: |
    /usr/local/bin/{{ cmd }} version | grep '^built from commit' | awk '{print $4}'
  register: commit_id
  tags: rhcospath

- name: Get the URLs
  set_fact:
    online_url: "https://raw.githubusercontent.com/openshift/installer/{{ commit_id.stdout }}/data/data/rhcos.json"
  tags: rhcospath

- name: Get RHCOS JSON File
  uri:
    url: "{{ online_url }}"
    return_content: yes
  until: rhcos_json.status == 200
  retries: 6 # 1 minute (10 * 6)
  delay: 10 # Every 10 seconds
  register: rhcos_json
  when: (the_url.status == 200)
  tags: rhcospath

- name: Set Facts for RHCOS_LIVE_URI and RHCOS_PATH
  set_fact:
    rhcos_live_uri: "{{ rhcos_json.json | json_query(iso_name) }}"
    rhcos_path: "{{ rhcos_json.json | json_query('baseURI') }}"
  vars:
    iso_name: 'images."live-iso".path'
  tags: rhcospath
