---
- name: Define DNS entries for dnsmasq
  copy:
    content: |
      address=/api.{{ cluster }}.{{ domain }}/{{ extcidrnet | ansible.netcommon.ipaddr('10') | ansible.netcommon.ipaddr('address') }}
      address=/.apps.{{ cluster }}.{{ domain }}/{{ extcidrnet | ansible.netcommon.ipaddr('10') | ansible.netcommon.ipaddr('address') }}
      address=/master1.{{ cluster }}.{{ domain }}/{{ extcidrnet | ansible.netcommon.ipaddr('10') | ansible.netcommon.ipaddr('address') }}
    dest: /etc/NetworkManager/dnsmasq.d/sno.conf
    owner: root
    group: root
  become: yes
  tags: dnsredirect

- name: Include dnsmasq in the DNS configuration of NetworkManager
  copy:
    content: "[main]\ndns=dnsmasq"
    dest: /etc/NetworkManager/conf.d/dnsmasq.conf
    owner: root
    group: root
  become: yes
  tags: dnsredirect

- name: Reload Network Manager
  service:
    name: NetworkManager
    state: reloaded
  become: yes
  tags: dnsredirect
